name: PR Verify

on:
  push:
    branches-ignore:
      - 'production'
      - 'development'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: PR Verify
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.0
      - name: yarn ci
        run: |
          yarn
          yarn ci